# Generated by Django 3.0.5 on 2020-04-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branches',
            new_name='branch',
        ),
    ]
