# Generated by Django 3.0.5 on 2020-04-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20200411_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank',
            new_name='banks',
        ),
        migrations.RenameModel(
            old_name='branch',
            new_name='branches',
        ),
        migrations.RenameField(
            model_name='banks',
            old_name='bank_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='banks',
            old_name='bank_name',
            new_name='name',
        ),
    ]
