# Generated by Django 3.0.5 on 2020-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_auto_20200411_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='id',
            field=models.IntegerField(default=True),
        ),
    ]
